SELECT nombre AS NOMBRE_PRODUCTO FROM producto;
SELECT nombre AS NOMBRE_PRODUCTO, precio AS PRECIO FROM producto; 
SELECT * FROM producto;
SELECT nombre AS NOMBRE_PRODUCTO, precio AS PRECIO_EUROS, precio*1.09 AS PRECIO_DOLARES FROM producto;
SELECT nombre AS NOM_DE_PRODUCTO, precio AS EUROS, precio*1.09 AS DOLARES FROM producto;
SELECT UCASE (nombre) AS NOM_DE_PRODUCTO, precio AS PRECIO FROM producto;
SELECT LCASE (nombre) AS NOM_DE_PRODUCTO, precio AS PRECIO FROM producto;
SELECT nombre AS NOMBRE_FABRICANTE, UCASE(substring(nombre,1,2)) FROM fabricante;
SELECT nombre AS NOMBRE_PRODUCTO, ROUND(precio) AS PRECIO FROM producto;
SELECT nombre AS NOMBRE_PRODUCTO, TRUNCATE(precio,0) AS PRECIO FROM producto;
SELECT f.codigo AS CODIGO_FABRICANTE FROM fabricante f JOIN producto p ON f.codigo=p.codigo_fabricante;
SELECT DISTINCT f.codigo AS CODIGO_FABRICANTE FROM fabricante f JOIN producto p ON f.codigo=p.codigo_fabricante;
SELECT nombre AS NOMBRE_FABRICANTE FROM fabricante ORDER BY nombre ASC;
SELECT nombre AS NOMBRE_FABRICANTE FROM fabricante ORDER BY nombre DESC;
SELECT nombre as NOMBRE_PRODUCTO FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3, 2;
SELECT nombre AS NOMBRE_PRODUCTO, precio AS PRECIO FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre AS NOMBRE_PRODUCTO, precio AS PRECIO FROM producto ORDER BY precio DESC LIMIT 1;
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.codigo=2;
SELECT p.nombre AS NOMBRE_PRODUCTO, p.precio AS PRECIO, f.nombre AS NOMBRE_FABRICANTE FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo;
SELECT p.nombre AS NOMBRE_PRODUCTO, p.precio AS PRECIO, f.nombre AS NOMBRE_FABRICANTE FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY f.nombre;
SELECT p.codigo AS CODIGO_PRODUCTO, p.nombre AS NOMBRE_PRODUCTO, f.codigo AS CODIGO_FABRICANTE, f.nombre AS NOMBRE_FABRICANTE FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo;
SELECT p.nombre AS NOMBRE_PRODUCTO, p.precio AS PRECIO, f.nombre AS NOMBRE_FABRICANTE FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY p.precio ASC limit 1;
SELECT p.nombre AS NOMBRE_PRODUCTO, p.precio AS PRECIO, f.nombre AS NOMBRE_FABRICANTE FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo ORDER BY p.precio DESC limit 1;
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo';
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Crucial' AND p.precio > 200;
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Asus' OR f.nombre='Hewlett-Packard' OR f.nombre='Seagate';
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre IN ('Asus', 'Hewlett-Packard','Seagate');
SELECT p.nombre AS NOMBRE_PRODUCTO, p.precio AS PRECIO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE '%e';
SELECT p.nombre AS NOMBRE_PRODUCTO, p.precio AS PRECIO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre LIKE '%w%';
SELECT p.nombre AS NOMBRE_PRODUCTO, p.precio AS PRECIO, f.nombre AS NOMBRE_FABRICANTE FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT f.codigo AS CODIGO_FABRICANTE, f.nombre AS NOMBRE_FABRICANTE FROM fabricante f JOIN producto p ON p.codigo_fabricante=f.codigo;
SELECT f.nombre AS NOMBRE_FABRICANTE, p.nombre AS NOMBRE_PRODUCTO FROM fabricante f LEFT JOIN producto p ON p.codigo_fabricante=f.codigo;
SELECT f.nombre AS NOMBRE_FABRICANTE, p.nombre AS NOMBRE_PRODUCTO FROM fabricante f LEFT JOIN producto p ON p.codigo_fabricante=f.codigo WHERE p.codigo is null;
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo';
SELECT * FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE p.precio =(SELECT MAX(p.precio) FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo');
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo' ORDER BY p.precio DESC LIMIT 1; 
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Hewlett-Packard' ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre AS NOMBRE_PRODUCTO FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE p.precio >=(SELECT MAX(p.precio) FROM producto p JOIN fabricante f ON p.codigo_fabricante=f.codigo WHERE f.nombre='Lenovo');

